import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next template</title>
        <meta name="description" content="Generated by me, myself, and I" />
      </Head>
      This is a test for testing purposes that tests a deployment in a way that
      is just for testing
    </div>
  );
};

export default Home;
